<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anwarrul Rizqi">
<meta name="dcterms.date" content="2025-01-14">

<title>Analisis Tantangan dan Peluang Indonesia terhadap Ekspor Karet ke Jepang sebagai Pasar Utama</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Tantangan dan Peluang Indonesia terhadap Ekspor Karet ke Jepang sebagai Pasar Utama</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anwarrul Rizqi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo APP</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Karet merupakan salah satu komoditi unggulan Indonesia karet indonesia menjadi produsen karet alam terbesar kedua di dunia, yang menjadikan sektor ini sebagai salah satu pilar utama dalam ekspor nonmigas. Jepang adalah salah satu pasar utama ekspor karet Indonesia, terutama untuk memenuhi kebutuhan industri otomotif, elektronik, dan manufaktur lainnya. Namun, ekspor karet ke Jepang menghadapi tantangan seperti fluktuasi nilai tukar, penurunan harga karet global, dan persaingan dengan negara lain seperti Thailand dan Vietnam. Di sisi lain, kebutuhan Jepang akan karet alam tetap stabil, menciptakan peluang untuk mempertahankan dan meningkatkan pangsa pasar.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini berfokus pada analisis tantangan dan peluang dalam ekspor karet Indonesia ke Jepang sebagai pasar utama, menggunakan data yang disediakan oleh Badan Pusat Statistik (BPS). Penilitian ini hanya mencakup karet Alam Indonesia, khususnya jenis karet remah (crumb rubber), yang merupakan salah satu produk ekspor unggulan ke jepang.Analisis ini juga dilakukan berdasarkan data ekspor dari tahun 2012-2023. Penelitian ini juga menganalisis faktor faktor yang mempengaruhi ekspor karet indonesia, seperti, Volume dan nilai ekspor karet indonesia , GDP Indonesia dan Jepang sebagai indikator kapasitas ekonomi dan nilai tukar Rupiah terhadap yen sebagai pengukur daya saing.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>-APA SAJA TANTANGAN UTAMA INDONESIA SEBAGAI PRODUSEN KARET DALAM MENGEKSPOR KARET KE JEPANG?</p>
<p>-APA PELUANG YANG DIMANFAATKAN UNTUK MENINGKATKAN EKSPOR KARET INDONESIA KHUSUSNYA KE JEPANG?</p>
<p>-BAGAIMANA FLUKTUASI HARGA KARET INTERNASIONAL MEMPENGARUHI DAYA SAING EKSPOR KARET INDONESIA DI PASAR JEPANG?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini diharapkan dapat, Memberikan wawasan yang lebih dalam mengenai tantangan yang harus dihadapi oleh Indonesia dalam mengoptimalkan ekspor karet ke Jepang. Menyediakan informasi tentang peluang yang dapat dimanfaatkan oleh pemerintah dan pelaku industri untuk meningkatkan kinerja ekspor karet Indonesia. Memberikan pemahaman tentang pengaruh fluktuasi harga karet internasional terhadap daya saing ekspor Indonesia, yang berguna dalam pengambilan keputusan ekonomi dan kebijakan perdagangan yang lebih efektif.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Perdagangan internasional adalah bagian yang penting dari kehidupan suatu negara. Ini terjadi karena perbedaan dalam sumber daya manusia, sumber daya alam, iklim, dan lokasi geografis, serta keadaan ekonomi dan sosial. Perbedaan ini menyebabkan barang yang dihasilkan, biaya yang diperlukan, dan kuantitas dan kualitas yang berbeda beda di setiap negara.Perdagangan Internasional dibagi menjadi dua kategori yaitu perdagangan barang dan perdagangan jasa. Kegiatan perdagangan Internasional dilakukan bertujuan untuk meningkatkan standar hidup negara tersebut (Schumacher, 2013).</p>
<p>Karet Karet merupakan salah satu komoditas hasil perkebunan yang mempunyai peran cukup penting dalam kegiatan perekonomian di Indonesia. Karet juga salah satu komoditas ekspor Indonesia yang dikenal sebagai penghasil devisa negara selain minyak dan gas. Indonesia merupakan negara produsen dan eksportir karet terbesar dunia.Dilihat dari Tanaman karet di Indonesia sendiri sebagian besar dikuasai oleh Perkebunan Rakyat yaitu sekitar 84,85%, sisanya 6,67% dikuasai Perkebunan Negara, dan 8,48% dikuasai Perkebunan Swasta. Pada tahun 2022 menurut angka estimasi Ditjenbun luas areal karet nasional meningkat 1,30% dari tahun 2021 (Angka Sementara), atau meningkat dari 3,78 juta hektar menjadi 3,83 juta hektar, sementara angka produksi karet meningkat 0,44% dari 3,12 juta ton tahun 2021, menjadi 3,13 juta ton tahun 2022.Sekitar 84,85% dari tanaman karet Indonesia dimiliki oleh Perkebunan Rakyat, dengan 6,67% dimiliki oleh Negara, dan 8,48% dimiliki oleh Perkebunan Swasta. Menurut estimasi Ditjenbun, luas areal karet nasional pada tahun 2022 meningkat 1,30% dari tahun 2021 (angka sedang), atau 3,78 juta hektar menjadi 3,83 juta hektar. Sementara itu, produksi karet meningkat 0,44% dari 3,12 juta ton pada tahun 2021 menjadi 3,13 juta ton pada tahun 2022.</p>
<p>Ekspor Ekspor merupakan bagian dari perdangan internasional,Ekspor sendiri adalah kegiatan menjual barang/jasa dari daerah pabean sesuai peraturandan undang-undang yang berlaku. Daerah pabean yang dimaksud ialahseluruh wilayah nasional dari suatu negara , diamana dipungut bea masuk dan bea keluar untuk semua barang-barang yang melewati wilayah tersebut.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian yaitu Berat Bersih X dan Y nilai FOB.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>X</th>
<th>Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>384.5</td>
<td>1238.80</td>
</tr>
<tr class="even">
<td>2013</td>
<td>419.3</td>
<td>1072.20</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>401.9</td>
<td>715.90</td>
</tr>
<tr class="even">
<td>2015</td>
<td>420.6</td>
<td>590.30</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>413.0</td>
<td>538.20</td>
</tr>
<tr class="even">
<td>2017</td>
<td>453.1</td>
<td>766.80</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>472.8</td>
<td>659.40</td>
</tr>
<tr class="even">
<td>2019</td>
<td>493.7</td>
<td>690.70</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>380.8</td>
<td>514.00</td>
</tr>
<tr class="even">
<td>2021</td>
<td>479.4</td>
<td>824.90</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>476.7</td>
<td>834.90</td>
</tr>
<tr class="even">
<td>2023</td>
<td>393.7</td>
<td>556.80</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>DATAEKSPOR <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/Asus/Desktop/Bahan Anwar/metopel (1)/metopel/dataexel.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data =</span> DATAEKSPOR)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = DATAEKSPOR)

Residuals:
    Min      1Q  Median      3Q     Max 
-237.99 -168.95  -46.42   78.73  486.93 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 764.91494  745.23927   1.026    0.329
X            -0.03393    1.71637  -0.020    0.985

Residual standard error: 230.7 on 10 degrees of freedom
Multiple R-squared:  3.908e-05, Adjusted R-squared:  -0.09996 
F-statistic: 0.0003908 on 1 and 10 DF,  p-value: 0.9846</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Asus/Desktop/Bahan Anwar/metopel (1)/metopel"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="ot">=</span><span class="fu">read_excel</span>(<span class="st">"dataexel.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>metopen,Y<span class="sc">~</span>X)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = metopen)

Residuals:
    Min      1Q  Median      3Q     Max 
-237.99 -168.95  -46.42   78.73  486.93 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 764.91494  745.23927   1.026    0.329
X            -0.03393    1.71637  -0.020    0.985

Residual standard error: 230.7 on 10 degrees of freedom
Multiple R-squared:  3.908e-05, Adjusted R-squared:  -0.09996 
F-statistic: 0.0003908 on 1 and 10 DF,  p-value: 0.9846</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(metopen<span class="sc">$</span>X,metopen<span class="sc">$</span>m, <span class="at">xlab=</span><span class="st">"Berat bersih (TON)"</span>, <span class="at">ylab =</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'green'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(DATAEKSPOR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  TAHUN     X     Y
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  2012  384. 1239.
2  2013  419. 1072.
3  2014  402.  716.
4  2015  421.  590.
5  2016  413   538.
6  2017  453.  767.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DATAEKSPOR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     TAHUN            X               Y         
 Min.   :2012   Min.   :380.8   Min.   : 514.0  
 1st Qu.:2015   1st Qu.:399.9   1st Qu.: 581.9  
 Median :2018   Median :419.9   Median : 703.3  
 Mean   :2018   Mean   :432.5   Mean   : 750.2  
 3rd Qu.:2020   3rd Qu.:473.8   3rd Qu.: 827.4  
 Max.   :2023   Max.   :493.7   Max.   :1238.8  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(DATAEKSPOR<span class="sc">$</span>X, DATAEKSPOR<span class="sc">$</span>Y, <span class="at">main =</span> <span class="st">"Scatter Plot Berat Bersih vs Nilai FOB"</span>,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Berat Bersih (ton)"</span>, <span class="at">ylab =</span> <span class="st">"Nilai FOB (USD)"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis yang saya gunakan dalam penelitian ini adalah Regresi Linear Sederhana,Metode ini bertujuan untuk menjelaskan hubungan antara satu variabel independen X (berat bersih/Net Weight) dan satu variabel dependen Y (nilai FOB).</p>
<p>Model yang akan digunakan:</p>
<p>𝑌=𝛽0+𝛽1𝑋+𝜖 <span class="math inline">\(Y\)</span>: Nilai FOB (USD).</p>
<p><span class="math inline">\(X\)</span>: Berat Bersih (ton).</p>
<p><span class="math inline">\(\beta_0\)</span>: Intersep.</p>
<p><span class="math inline">\(\beta_1\)</span>: Koefisien regresi (pengaruh berat bersih terhadap nilai FOB).</p>
<p><span class="math inline">\(\epsilon\)</span>: Error term.</p>
<p>Dengan Metode ini penelitian dengan Regresi digunakan untuk memperkirakan nilai variabel dependen (𝑌) berdasarkan nilai variabel independen (𝑋).</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Aspek</th>
<th>Koefisien / Nilai</th>
<th>Std. Error</th>
<th>t-value</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residuals</td>
<td>-642883, 5111, …</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>11,657,572.4</td>
<td>1,295,923.6</td>
<td>8.996</td>
<td>0.000845</td>
</tr>
<tr class="odd">
<td>X (Jumlah Ekspor Karet ke Jepang)</td>
<td>-419.7</td>
<td>245.9</td>
<td>-1.707</td>
<td>0.163050</td>
</tr>
<tr class="even">
<td>S (PDB Indonesia)</td>
<td>401.4</td>
<td>308.0</td>
<td>1.303</td>
<td>0.262394</td>
</tr>
<tr class="odd">
<td>Residual Standard Error</td>
<td>725,600</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Multiple R-squared</td>
<td>0.4458</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.1687</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>F-statistic</td>
<td>1.609</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>Koefisien untuk X (jumlah ekspor karet ke Jepang) adalah -419.7, yang berarti bahwa setiap kenaikan satu ton ekspor karet dapat menyebabkan penurunan PDB Indonesia sebesar 419.7. Namun, p-value untuk koefisien ini adalah 0.163050, yang lebih besar dari 0.05, menunjukkan bahwa jumlah ekspor karet tidak signifikan dalam mempengaruhi PDB Indonesia. Ini berarti meskipun ada hubungan negatif antara ekspor karet dan PDB, hubungan ini tidak cukup kuat atau signifikan dalam model ini.</p>
<p>Koefisien untuk S (PDB Indonesia) adalah 401.4, yang menunjukkan bahwa setiap kenaikan satu unit nilai FOB karet dapat meningkatkan PDB Indonesia sebesar 401.4. Meskipun ada hubungan positif yang terindikasi antara nilai FOB dan PDB, p-value untuk koefisien ini adalah 0.262394, lebih besar dari 0.05, yang menandakan bahwa nilai FOB tidak signifikan dalam mempengaruhi PDB Indonesia. Jadi, meskipun ada indikasi hubungan positif, ini tidak cukup signifikan dalam model ini.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data =</span> DATAEKSPOR)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = DATAEKSPOR)

Residuals:
    Min      1Q  Median      3Q     Max 
-237.99 -168.95  -46.42   78.73  486.93 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 764.91494  745.23927   1.026    0.329
X            -0.03393    1.71637  -0.020    0.985

Residual standard error: 230.7 on 10 degrees of freedom
Multiple R-squared:  3.908e-05, Adjusted R-squared:  -0.09996 
F-statistic: 0.0003908 on 1 and 10 DF,  p-value: 0.9846</code></pre>
</div>
</div>
<p>Koefisien untuk Intersep (<span class="math inline">\(\beta_0\)</span>): 764.91. Artinya, jika berat bersih adalah 0, nilai FOB diperkirakan <span class="math inline">\(764.91\)</span> USD. Koefisien berat bersih (X) (<span class="math inline">\(\beta_1\)</span>): -0.03393. Ini menunjukkan bahwa setiap kenaikan 1 ton berat bersih, nilai FOB cenderung menurun sebesar <span class="math inline">\(0.03393\)</span> USD. Namun, koefisien ini tidak signifikan (p-value = 0.985). Untuk X: 0.985 (jauh lebih besar darI (0.05). Artinya, koefisien 𝑋tidak signifikan secara statistik. Berat bersih tidak memiliki pengaruh yang signifikan terhadap nilai FOB dalam model ini. Untuk model keseluruhan (F-statistik): 0.9846 (juga jauh lebih besar dari 0.05). Artinya, model secara keseluruhan tidak signifikan dalam menjelaskan hubungan antara berat bersih dan nilai FOB.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Penelitian ini memberikan wawasan mengenai tantangan dan peluang dalam ekspor karet Indonesia ke Jepang. Meskipun hasil regresi menunjukkan bahwa variabel ekspor karet dan nilai FOB tidak memiliki pengaruh signifikan terhadap PDB Indonesia, tantangan seperti fluktuasi harga karet global dan persaingan dengan negara lain tetap perlu diperhatikan. Di sisi lain, kebutuhan Jepang akan karet alam yang stabil memberikan peluang bagi Indonesia untuk meningkatkan pangsa pasar. Oleh karena itu, meskipun hubungan antara variabel yang dianalisis tidak signifikan, pengelolaan yang tepat terhadap faktor-faktor eksternal dapat meningkatkan kinerja ekspor karet Indonesia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Wijoyo, A., Annie .S , N., &amp; Hazmi , A. (2025). PERDAGANGAN INTERNASIONAL. Neraca: Jurnal Ekonomi, Manajemen Dan Akuntansi, 3(4), 405–411 . Retrieved from https://jurnal.researchideas.org/index.php/neraca/article/view/127</p>
<p>Badan Pusat Statistik Provinsi Dki Jakarta. (1 Desember 2022). Karet Komoditas Unggulan Indonesia. Diakses pada 13 Januari 2025, dari https://jakarta.bps.go.id/id/news/2022/12/01/823/karet-komoditas-unggulan-indonesia.html</p>
<p>https://satudata.pertanian.go.id/assets/docs/publikasi/Outlook_Karet_2022_ttd.pdf</p>
<p>Kementerian Perdagangan Republik Indonesia. (2023). Laporan Perdagangan Karet Indonesia ke Pasar Dunia. Diakses dari: https://www.kemendag.go.id</p>
<p>World Bank. (2024). Indonesia’s Export Competitiveness in Rubber. Retrieved from: https://www.worldbank.org</p>
<p>Kementerian Perindustrian Republik Indonesia. (2022). Pengaruh Fluktuasi Harga Karet Global terhadap Industri dalam Negeri. Available at: https://www.kemenperin.go.id</p>
<p>ASEAN Economic Community. (2022). The Role of ASEAN in Rubber Trade in Asia. Diakses pada 12 Januari 2025, dari: https://asean.org</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>